#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import subprocess

fs_type = ""

if len(sys.argv) >= 3 :
    
    initrd_f = open(sys.argv[2], "r")
    fs_type  = initrd_f.read(4)
    initrd_f.close()

    if fs_type != "hsqs":
         sys.exit(0)

sys.argv[0] = "/usr/bin/mksquashfs.bin"
subprocess.call(sys.argv)
